# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on: 
  push:
    branches: [Produccion]
      
name: 🚀 Deploy SISAD
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.USER_PASS }}
        port: ${{ secrets.HOST_PORT }}
        exclude: |
          **/.git/** 
          README.md